name: Helloworkflow

on: [push]

jobs:
 Hello:
  runs-on: ubuntu-latest
  steps:
    - name: ShowMessage 
      run: echo "Hello Workflow"
    - name: ListDir
      run: ls -alh
    - name: Checkout
      uses: actions/checkout@v4